// scripts/generate-readme.js
// Fetches all public repos in the org, groups them by difficulty topic,
// and regenerates profile/README.md with shields.io badges.

import { Octokit } from "@octokit/rest";
import { writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

const ORG = process.env.ORG_NAME;
const TOKEN = process.env.GITHUB_TOKEN;

if (!ORG || !TOKEN) {
  console.error("Missing ORG_NAME or GITHUB_TOKEN environment variables.");
  process.exit(1);
}

const octokit = new Octokit({ auth: TOKEN });

// Difficulty levels — order controls section order in the README
const DIFFICULTIES = ["newbie", "junior", "intermediate", "advanced", "guru"];

// Badge colour per difficulty
const COLOURS = {
  newbie: "06b6d4",
  junior: "34d399",
  intermediate: "fbbf24",
  advanced: "f97316",
  guru: "e11d48",
};

async function fetchAllRepos() {
  const repos = [];
  let page = 1;

  while (true) {
    const { data } = await octokit.repos.listForOrg({
      org: ORG,
      type: "public",
      per_page: 100,
      page,
    });

    if (data.length === 0) break;
    repos.push(...data);
    page++;
  }

  return repos;
}

async function fetchTopics(repoName) {
  const { data } = await octokit.repos.getAllTopics({
    owner: ORG,
    repo: repoName,
  });
  return data.names || [];
}

function makeBadge(repo, difficulty) {
  const colour = COLOURS[difficulty];
  const label = repo.name.replace(/-/g, "_");
  const badgeUrl = `https://img.shields.io/badge/${difficulty}-${label}-${colour}?style=flat`;
  const repoUrl = repo.html_url;
  return `[![${repo.name}](${badgeUrl})](${repoUrl})`;
}

function buildReadme(grouped, totalCount) {
  const now = new Date().toLocaleDateString("en-GB", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  const difficultyBreakdown = DIFFICULTIES.filter((d) => grouped[d]?.length > 0)
    .map((d) => `**${grouped[d].length}** ${d}`)
    .join(" &nbsp;·&nbsp; ");

  const sections = DIFFICULTIES.filter((d) => grouped[d]?.length > 0)
    .map((d) => {
      const badges = grouped[d].map((r) => makeBadge(r, d)).join("\n");
      const title = d.charAt(0).toUpperCase() + d.slice(1);
      return `### ${title}\n\n${badges}`;
    })
    .join("\n\n---\n\n");

  return `# Frontend Mentor Projects

This organization contains my solutions to [Frontend Mentor](https://www.frontendmentor.io) challenges.
I use these projects to improve my design thinking and frontend development skills, while also
experimenting with new CSS features and techniques.

---

## Goals

- 🎨 Improve design thinking and UI implementation
- 💪 Strengthen core frontend skills
- ✨ Experiment with modern CSS features
- 🧹 Build clean, maintainable solutions

---

## Tech Stack

| Layer | Tools |
|---|---|
| Markup | Semantic HTML |
| Styling | Vanilla CSS *(primary focus)* |
| Behaviour | JavaScript *(when needed)* |
| Frameworks | Used occasionally to practice specific ones |

---

## Challenges — ${totalCount} completed

${difficultyBreakdown}

${sections}

---

<sub>Last updated ${now} · Auto-generated by <a href="./.github/workflows/update-readme.yml">GitHub Actions</a></sub>
`;
}

async function main() {
  console.log(`Fetching repos for org: ${ORG}`);
  const repos = await fetchAllRepos();
  console.log(`Found ${repos.length} public repos`);

  const grouped = Object.fromEntries(DIFFICULTIES.map((d) => [d, []]));
  let totalCount = 0;

  for (const repo of repos) {
    // Skip the .github meta-repo itself
    if (repo.name === ".github") continue;

    const topics = await fetchTopics(repo.name);
    const difficulty = DIFFICULTIES.find((d) => topics.includes(d));

    if (!difficulty) {
      console.log(`  Skipping "${repo.name}" — no difficulty topic found`);
      continue;
    }

    console.log(`  ${repo.name} → ${difficulty}`);
    grouped[difficulty].push(repo);
    totalCount++;
  }

  // Sort repos within each difficulty alphabetically
  for (const d of DIFFICULTIES) {
    grouped[d].sort((a, b) => a.name.localeCompare(b.name));
  }

  const readme = buildReadme(grouped, totalCount);
  const outputPath = join(__dirname, "../profile/README.md");
  writeFileSync(outputPath, readme, "utf8");
  console.log(`\nREADME written to ${outputPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
